#!/bin/zsh
set -uo pipefail

printf "Running pacman update...\n"
sudo pacman -Syu;

printf "Removing orphans...\n"
sudo pacman -Rns $(pacman -Qtdq)
yay -Yc

printf "Cleaning pacman cache...\n"
sudo pacman -Sc
  
printf "Cleaning user cache...\n"
rm -rf ~/.cache/
