#! /bin/bash
wttr=$(curl -sf 'https://pl.wttr.in/Łańcut?format=%l:+%C,+%f,+%P,+%h&lang=pl')
globIP=$(curl -s ifconfig.me)
#sed -i "1s/.*/foo=$wttr" /home/juchap/.slstatus/.slbar.txt
#sed -i "2p $globIP" /home/juchap/.slstatus/.slbar.txt
echo -e "$wttr" > /home/juchap/.slstatus/.wttr.txt
echo -e "$globIP" > /home/juchap/.slstatus/.ip.txt
