#! /bin/bash
while true;
do
  wttr=$(curl -sf 'https://pl.wttr.in/Łańcut?format=%l:+%C,+%f,+%P,+%h&lang=pl')
  globIP=$(curl -s ifconfig.me)
  echo -e "$wttr" > /home/juchap/.slstatus/.wttr.txt
  echo -e "$globIP" > /home/juchap/.slstatus/.ip.txt
  sleep 5m
done
